export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const REQUEST_GET_USERL_ONE_SUCCESS = 'REQUEST_GET_USERL_ONE_SUCCESS';


export const REQUEST_ATTACHMENT_LIST_SUCCESS = "REQUEST_ATTACHMENT_LIST_SUCCESS";